[fms]
remote_control = true

[timing]
auto_time_seconds = 0
teleop_time_seconds = 100
endgame_time_seconds = 15

[sounds]
volume = 1

[event]
event_name = "ECOINGENIA 2025"
matches_file = "./ecoingenia_matches.csv"
save_directory = "./matches_results"

